log_exporter_command: "/usr/bin/python3 /opt/support/log_exporter/BKM100_support.py >> /var/log/log_exporter/BKM100_support.log 2>&1"

cron_jobs:
  - name: "log_exporter_retry.sh weekday"
    user: root
    minute: "0"
    hour: "2"
    day: "*"
    weekday: "1-5"
    job: "/usr/local/bin/log_exporter/log_exporter_retry.sh -scp > /dev/null 2>&1"
    
  - name: "log_exporter.sh weekday"
    user: root
    minute: "30"
    hour: "3"
    day: "*"
    weekday: "1-5"
    job: "/usr/local/bin/log_exporter/log_exporter.sh -scp > /dev/null 2>&1"
