- name: Ensure script directory exists
  file:
    path: /usr/local/bin/log_exporter/
    state: directory

- name: Template script files and copy to the target hosts
  template:
    src: "{{ item }}"
    dest: "/usr/local/bin/log_exporter/{{ item | regex_replace('\\.j2$', '') }}.sh"
    mode: "0755"
  with_items:
    - "log_exporter.j2"

- name: Copy non-template script file to the target hosts
  copy:
    src: "./log_exporter_retry.sh"
    dest: "/usr/local/bin/log_exporter/log_exporter_retry.sh"
    mode: "0755"
