---
- hosts: all
  tasks:
    - name: ssh-keygen on ansible controller
      ansible.builtin.include_role:
        name: control-node-ssh-keygen/tasks/main.yml

    - name: fingerprint-accept of remote host
      ansible.builtin.include_role:
        name: fingerprint-accept
        
    - name: ssh-key-upload to remote host
      ansible.builtin.include_role:
        name: ssh-key-upload
