- name: Ensure remote directory exists
  file:
    path: "{{ remote_dir }}"
    state: directory
- name: Ensure unzip is installed
  package:
    name: unzip
    state: present

- name: Upload and extract audit script
  unarchive:
    src: "{{ zip_local_path }}"
    dest: "{{ remote_dir }}"
    remote_src: no
    
- name: Upload and extract audit script
  unarchive:
    src: "{{ zip_local_path }}"
    dest: "{{ remote_dir }}"
    remote_src: no

- name: Set script permissions
  file:
    path: "{{ remote_dir }}/bpksecurityauditscanner/{{ script_name }}"
    mode: '0755'

- name: Install required packages
  ansible.builtin.package:
    name:
      - hostname
      - net-tools  # This package provides netstat
      - zip
    state: present

- name: Install OpenSCAP
  ansible.builtin.package:
    name: openscap-scanner  # The package name might differ based on your OS
    state: present

